name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIG: 'Release'
      NAME: 'FluentVault'

    steps:
    - uses: actions/checkout@v2
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1 -Force
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test "($Name).UnitTests" -c $BUILD_CONFIG --no-build --verbosity normal
